# Generated by Django 4.2.4 on 2023-10-13 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_foodrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrequest',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.account'),
        ),
    ]
