# Generated by Django 4.2.4 on 2023-10-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_account_fake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='fake',
        ),
    ]
