# Generated by Django 4.2.6 on 2023-10-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_account_fake'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foodRequest',
            new_name='order',
        ),
    ]
